### ISSUE TITLE
How do you contiunue on someone elses work?

### ISSUE THREAD

**Issue by LegacyID1991** [mindbender-studio/core#37]
When you publish, you export from you work what the next artist needs.

What happens when you do a hand over ? when you have done 80 % of the job and the next artist is suppose to complete it.

Can we create an extra option in the loader to load the _".source"_ instead of the export ?

**Comment by mottosso** [comment]
It's safe to browse directly to another artists work directory and pick it up from there.

Nothing about work folders is pipelined and doesn't need to be. K-I-S-S.

**Comment by LegacyID1991** [comment]
what about the sync?
since we only sync the published folder.

**Comment by LegacyID1991** [comment]
I guess that wont help either way but since not all artist have the exact same setup, example a freelancer using mindbendersetup then their workfiles wont always have the same filepath. then it would be nice to have a _source_ file that is in a _.ma_ format so that you can go in with a text editor and change those filepath with search & replace.
And then you can start your own work file and load that scene in, and continue working.

**Comment by mottosso** [comment]
There is no avoiding having to personally pass one workfile from one artist to another, since as you say, the artists have different styles of working. It would be impractical to try and pipeline a way to pass such files between artists. At best you could log it to keep track of when, why and how.

For artists working remotely, I'd ask them to simply browse to a shot or asset, and then get sent the workfile they are meant to continue with. Either directly via the server, or Skype etc.

As for differing file paths, I thought you asked your remote artists to set-up an `m:\` of their own? That way paths would always remain the same. If this isn't the case already, I'd make that a priority.

**Comment by mottosso** [comment]
Some additional discussion via Skype.

1. It can sometimes be beneficial to continue on someone elses work when they are not around to hand it to you. For example, someone in Brazil has delivered an update last-minute, deadline is approaching and something needs fixing.
2. Opening of the published `source` file can be unstable. For example, if the workfile depends on files from an artists personal workfolder, such as textures or caches. Files that would normally be baked into the asset on publish.

**Comment by mottosso** [comment]
If this is still a problem, feel free to re-open this thread.
