### ISSUE TITLE
Validate Single Assembly

### ISSUE THREAD

**Issue by LegacyID1991** [mindbender-studio/core#49]
When trying to publish a rig [_Validate Single Assembly_](https://github.com/mindbender-studio/core/blob/master/mindbender/maya/plugins/validate_single_assembly.py) shows error.
This is the outliner for this scene:

| Maya Outliner                                                  |
|-----------------------------------------------------------|
|  &#8194; box01_:modelDefault<br> &#9500;&#9472;&#8194; box01_:ROOT<br> &#9474; &#9492;&#9472;&#8194; box01_:MESH <br> &#9474; &#8194;&#8194; &#9492;&#9472;&#8194; box01_:BOX <br><br> &#8194; ROOT <br> &#9500;&#9472;&#8194; MESH <br> &#9474; &#9492;&#9472;&#8194; box_1 <br> &#9500;&#9472;&#8194; OUT <br> &#9474; &#9492;&#9472;&#8194; box_2 <br> &#9500;&#9472;&#8194; DATA <br> &#9474; &#9492;&#9472;&#8194; joint1<br> &#9500;&#9472;&#8194; Controls <br> &#9474; &#9492;&#9472;&#8194; nurbsCircle1<br><br>  &#8194; rigDefault_SET<br> &#9500;&#9472;&#8194; ROOT<br> &#9500;&#9472;&#8194; controls_SET<br> &#9474; &#9492;&#9472;&#8194; nurbsCircle1<br> &#9500;&#9472;&#8194; out_SET<br> &#9474; &#9492;&#9472;&#8194; box_2<br> |
|                                                           |
![capture160](https://cloud.githubusercontent.com/assets/24475296/23121765/eaddf0dc-f761-11e6-8eac-7705baf8eacb.PNG)

**Comment by LegacyID1991** [comment]
When compairing old version of this file I find:


old file has 

```
        assemblies = cmds.ls(instance, assemblies=True)
```
new file has

```
        assemblies = cmds.ls(nodes, assemblies=True)
```

new command for assemblies produces:
```
> # Error: NameError: file <maya console> line 1: name 'nodes' is not defined #
```

**Comment by mottosso** [comment]
Rather than deleting comments, it'd better if you could make another comment, saying the previous comment is wrong. Everyone subscribed to threads will receive emails with previous comments, and not seeing them here can be quite confusing.

**Comment by LegacyID1991** [comment]
Didn't think of that.

**Comment by mottosso** [comment]
Here's a tip for when posting bug reports.

The fastest and easiest way for someone else to fix a problem is for them to be able to reproduce the problem themselves. So with every bug report there should *ideally* be a snippet of code that completely reproduces the problem.

Here's an example.

```python
from maya import cmds
from mindbender import maya, api

cmds.file(new=True, force=True)

cube = cmds.polyCube(name="myCube_GEO")
assembly = cmds.group(name="ROOT")

container = maya.create(
    "modelDefault",
    family="mindbender.model",
    options={"useSelection": True}
)

cmds.file(rename="temp.ma")
cmds.file(save=True)

import pyblish_qml
pyblish_qml.show()
```

In this example, I do everything a modeler would do in order to publish a model. Running this, you can clearly see my line of thinking and potentially spot any problems in workflow.

In this case, I do not get the problem, which also makes it clear to me that the problem is more complex and that I will have to look elsewhere.

In the next example, I..

1. Create a new reference, 
2. Import said reference
3. Make a clone, leaving the original where it was in the hierarchy
4. Create a model of this clone
5. Attempt to publish

```python
from maya import cmds
from mindbender import maya, api
from mindbender.maya import commands

# Create a new reference target
cmds.file(new=True, force=True)
cube = cmds.polyCube(name="myCube_GEO")
cmds.file("reference.ma", exportSelected=True, force=True, typ="mayaAscii")

cmds.file(new=True, force=True)
nodes = cmds.file("reference.ma", reference=True, returnNewNodes=True)
mesh = next(node for node in nodes if cmds.nodeType(node) == "mesh")
clone = commands.clone(mesh)
cmds.select(clone, replace=True)
assembly = cmds.group(name="ROOT")

container = maya.create(
    "modelDefault",
    family="mindbender.model",
    options={"useSelection": True}
)

cmds.file(rename="temp.ma")
cmds.file(save=True)

import pyblish_qml
pyblish_qml.show()
```

In this case, the assembly validator is triggered. And it is right to do so, because in this case, publishing this asset, would result in two top-level nodes (i.e. assemblies). One being your model, and the other being the original reference.

The validator is correct, the solution is to group the original asset with your new asset.

Let me know if that works for you.

**Comment by LegacyID1991** [comment]
This code worked for me.
But how would this work with a rig.
because you need to load in a published model.

![capture161](https://cloud.githubusercontent.com/assets/24475296/23158241/b9d33174-f81e-11e6-9a43-a264d517a4ca.PNG)

Would you delete the reference before publishing or ?

**Comment by mottosso** [comment]
You can include the `box01_:modelDefault` group *inside* of `ROOT`.

**Comment by mottosso** [comment]
The reason it is being picked up, is because there is history between something in `ROOT` and the `box01_` reference. Maya doesn't attempt to break connections between nodes, because if it did your rig might break.

Instead, it chooses to include everything connected to your rig, which is why the validation fails.

On the other hand, it is safe to have other assemblies, so long as they are not physically connected to what you are publishing.

Does that make sense?

**Comment by LegacyID1991** [comment]
It does,

How come this worked differently before ?
If this is the new workflow and it works then I got no problems with it..

**Comment by mottosso** [comment]
From the [original commit](https://github.com/mindbender-studio/core/commit/f21cd7a9d2c84a6f1590680ecb6ad9cbcea17b8b) you can see that before, it wasn't test-exporting the file to see what Maya considered part of history. It just took whatever nodes the artist had chosen to be part of the instance, and trusted this to be accurate.

The new version physically exports the file, so there is nowhere for history to hide. The result is quite accurate.

**Comment by LegacyID1991** [comment]
I see.

what I ment by 
> how come this worked differently before ?

was that before you didn't need to include the loaded model inside of Root. 
And I guess a better question will be will this affect anything else down the line or will this new workflow for riggers work across the board ?

**Comment by mottosso** [comment]
> was that before you didn't need to include the loaded model inside of Root.

Yes, I know, I meant the same thing. Before, the validator wasn't smart enough to know that there was a connection.

This should definitely be the mandatory workflow for everyone, otherwise when you import an asset, you would get multiple top-level nodes and you only want `ROOT`. Nothing else.

**Comment by LegacyID1991** [comment]
That is exactly what I wanted to hear.
Make it soo..
