### ISSUE TITLE
Organizing Work folders

### ISSUE THREAD

**Issue by CalleHalldin** [mindbender-studio/core#68]
### Goal

Simplify finding the latest working file.

### Motivation

Right now on the current project you constantly have to check all "working folders" - such as `calle/maya/`, `arvid/maya/` and `emre/maya` - to find the latest file which becomes time consuming.

It is a cause of the kind of mistakes where you accidentally open up a version that you think is the latest but isn't.

At our company we share a lot of files between artists so it might be a better idea to group them altogether and treat the company as one big user.

### Implementation

Remove the `user/` directory from the `work/` directory.

```bash
# Before
Bruce/work/modeling/calle/maya/...

# After
Bruce/work/modeling/maya/...
```

Users would  then be responsible for keeping up with a naming convention for their scene files that reflect their intentions and can no longer store files that are personal to themselves in the work directory.

**Comment by mottosso** [comment]
Do take a moment to format your text and keep it objective, it'll save time for everyone reading it.

For posterity, here is the original.

> Right now on the current project you constantly have to check all "Working folders" to find the latest file and there are sometimes 3 or more of them which becomes time consuming and frankly annoying.
it also feels like this way can cause mistakes where you accidentally open up a version that is the latest because you simply missed it or different users naming convention confuses you, which kinda defeats the purpose of a pipeline.
In an ideal world one artist works on one assets for the specific task until its done but that rarely happens in the land of commercials or other fast moving productions, things can be very dynamic. At least at our company.

**Comment by CalleHalldin** [comment]
Alright, i will try :)
Update for this part, 
_Users would then be responsible for keeping up with a naming convention for their scene files that reflect their intentions and can no longer store files that are personal to themselves in the work directory._ 

It would be nice if we could simply have Save function within the pipeline that saves it with som standard name convention?

**Comment by mottosso** [comment]
> It would be nice if we could simply have Save function within the pipeline that saves it with som standard name convention?

That wouldn't be a problem technically, what I'm trying to steer us clear from is building a dependency on the way people work. I'm of the belief that a pipeline should accommodate various styles of working, and organising your own files is a big part of that.

We could add such a button and say to simply use it as a visual guide for when we look for files, but it opens up a temptation to go further, and build tools that perhaps automatically open files and from there we open up for much greater frustration than finding peoples files. At that point, we would limit anyone from simply saving files in a way that the pipeline hasn't foreseen. "Can I save manually, will it break the pipeline?"

I've been in pipelines like this and though built with the best of intentions, it is no fun.

At the moment, you can save files in any way imaginable. The only filter is on output - publishing. What I have in mind for you in sharing files is not to open up each other's workfiles, but to share files by publishing. We haven't gotten there yet, so it is understandably frustrating at this point. But bear with me.

On the topic of this issue however, since we haven't built anything on-top of workfiles in terms of pipeline, making this change is simple and can be made without breaking your running projects. It would be a matter of @LegacyID1991 removing the `work` subfolder from the `.bat` files and then you would all be saving into a common folder per task.

This flexibility is precisely the reason I didn't want to build on-top of working habits.

**Comment by CalleHalldin** [comment]
Alright sounds reasonable!
Alright Cool, I'm happy it's such an easy fix aswell.

**Comment by LegacyID1991** [comment]
So I am to remove the username folder between Task folder and Application folder ?

**This:**
> _projectPath_/**assets**/_assetName_/work/_userName_/_maya_
> **.../p356_DoctorWho_season50_2032/assets/tardis/work/Calle/maya**

**Becomes:**
> _projectPath_/**assets**/_assetName_/**work**/_maya_
> **.../p356_DoctorWho_season50_2032/assets/tardis/work/maya**

or have I misunderstood this issue ?

**Comment by mottosso** [comment]
That's it! Give it a try and the pull request.

**Comment by CalleHalldin** [comment]
Looking at the example legacy provided, this won't remove the task folder I hope? /work/_rigging_/maya ?

**Comment by mottosso** [comment]
Yeah, the example isn't quite right. Only the user folder is to be discarded.

**Comment by LegacyID1991** [comment]
**This:**
> _projectPath_/**assets**/_assetName_/work/_taskName_/_userName_/_maya_
> **.../p356_DoctorWho_season50_2032/assets/tardis/work/animation/Calle/maya**

**Becomes:**
> _projectPath_/**assets**/_assetName_/**work**/_taskName_/_maya_
> **.../p356_DoctorWho_season50_2032/assets/tardis/work/animation/maya**

How is that ?

**Comment by LegacyID1991** [comment]
And a though I had.

Instead of removing the user folder, how about instead of it being a user folder, make it a **ALL** folder.
That way we keep the current folder structure just change that everyone saves in a **studio** folder

**This:**
> _projectPath_/**assets**/_assetName_/**work**/_taskName_/_userName_/_maya_
> **.../p356_DoctorWho_season50_2032/assets/tardis/work/animation/Calle/maya**

**Becomes:**
> _projectPath_/**assets**/_assetName_/**work**/**studio**/_taskName_/_maya_
> **.../p356_DoctorWho_season50_2032/assets/tardis/work/**studio**/animation/maya**

We can call the folder **ALL** we can call it **studio** it could be whatever but most importantly this would mean that we dont change structure just add another static folder name to the API.

What do you think ?

**Comment by mottosso** [comment]
I don't see the point.

The structure of the work folders aren't considered in the pipeline at all, so changing them isn't a problem.

**Comment by mottosso** [comment]
Paths can now be customised via a `path template`.

```python
"{root}/{project}/{silo}/{asset}/work/{task}/{user}/{app}"
```

- https://mindbender-studio.github.io/journal/p/week-7/#managing-projects
